### ISSUE TITLE
Geocode upgrade item count doesn't match

### ISSUE THREAD

**Issue by juho-jaakkola** [hypeJunction/hypeMapsOpen#5]
![image](https://cloud.githubusercontent.com/assets/883920/22630355/f59a598a-ebf8-11e6-991f-45d3b04c120d.png)

**Comment by hypeJunction** [comment]
@juho-jaakkola Was this fixed in the PR?

**Comment by juho-jaakkola** [comment]
Nope

**Comment by hypeJunction** [comment]
I don't care to be honest. The whole upgrade logic is so hacky that I'd rather wait till 3.0 to do anything with it.

**Comment by juho-jaakkola** [comment]
Agreed
